#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

typedef enum TokenTypes {
    TOKEN_PAREN_LEFT,
    TOKEN_PAREN_RIGHT,
    TOKEN_BRACE_LEFT,
    TOKEN_BRACE_RIGHT,
    TOKEN_SEMICOLON,
    TOKEN_COMMA,
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH,
    TOKEN_VAR,
    TOKEN_FN,
    TOKEN_IF, TOKEN_ELSE,
    TOKEN_WHILE,
    TOKEN_TRUE, TOKEN_FALSE,
    TOKEN_RETURN,
    TOKEN_NUMBER,
    TOKEN_CHARACTER,
    TOKEN_IDENTIFIER,
    TOKEN_EOF,
    TOKEN_ERROR
} TokenType;

typedef enum Types {
    TYPE_INT,
    TYPE_INT_PTR,
    TYPE_CHAR,
    TYPE_CHAR_PTR,
    TYPE_BYTE,
    TYPE_BYTE_PTR,
    TYPE_BOOL,
    TYPE_BOOL_PTR,
    TYPE_UNKNOWN
} Type;

#endif // TOKEN_TYPE_H
